export const APP_NAME = 'CineBook'
export const APP_TAGLINE = 'Book Your Movie Experience'
export const API_BASE_URL = ''
export const DEFAULT_LANGUAGE = 'en'
export const CURRENCY = 'USD'
export const CURRENCY_SYMBOL = '$'
