export const APP_NAME = 'CineBook'
export const APP_TAGLINE = 'Book Your Movie Experience'
export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'http://localhost:9898'
export const DEFAULT_LANGUAGE = 'en'
export const CURRENCY = 'USD'
export const CURRENCY_SYMBOL = '$'
